# Information provided by: Battler
# At http://lbafileinfo.kazekr.net/index.php?title=LBA2:Body.hqr
# coding=utf-8
body_names = ['Twinsen without tunic model',
              'Twinsen with tunic model',
              'Twinsen with tunic and sword model',
              'Twinsen with tunic and blowgun model',
              'Twinsen with tunic and blowtron model',
              'Twinsen with tunic and wannie glove model',
              'Twinsen with tunic and laser pistol model',
              'Twinsen with wizard\'s tunic model',
              'Twinsen with wizard\'s tunic and blowgun model',
              'Twinsen with tunic (darker shading) model',
              'Twinsen with tunic (darker shading) and pick-axe model',
              'Twinsen with tunic (darker shading) and portable radio model',
              'Twinsen burning model',
              'Twinsen falling in Dome of the Slate model',
              'Twinsen with tunic and car closed model',
              'Twinsen with wizard\'s tunic and car closed model',
              'Twinsen with tunic and protopack model',
              'Twinsen with tunic and Zoé model',
              'Twinsen with tunic and Horn of Blue Triton model',
              'Twinsen with wizard\'s tunic and Horn of Blue Triton model',
              'Twinsen with space suit model',
              'Twinsen with tunic and super jetpack model',
              'Twinsen with tunic and car open model',
              'Twinsen with wizard\'s tunic and car open model',
              'Twinsen X-Rayed model',
              'Nitro-meca-penguin model',
              'Zoé model',
              'Zoé with umbrella model',
              'Piece of flying saucer model',
              'Dot model',
              'Holomap model',
              'Three darts model',
              'Raph, the lighthouse keeper model',
              'The Tralu model',
              'Snake model',
              'Rabbibunny skeleton model',
              'The flying rat model',
              'The quetch not being from Citadel Island model',
              'Drunk rabbibunny in Luc\'s bar model',
              'Luc, the boss model',
              'Tim, waiter model',
              'A sphero (Raph\'s friend) model',
              'Another sphero model',
              'A third sphero model',
              'Quetch girl, Raph\'s friend model',
              'Quetch girl, Raph\'s friend model',
              'Sup in light green dressing model',
              'Sup in light green dressing with gun model',
              'Sup in light green dressing with newspaper model',
              'Yellow franco with green pistol model',
              'Yellow franco with red pistol model',
              'Gray esmer dog without mouth protection model',
              'Gray esmer dog with mouth protection model',
              'Brown esmer dog without mouth protection model',
              'Grobo in the baggage claim model',
              'Propeller of the crate-moving apparatus model',
              'Rabbibunny in the baggage claim model',
              'Crate-pushing apparatus model',
              'Quetch in the baggage claim model',
              'Mr. Paul model',
              'Grobo no. 1 in Temple of Bu model',
              'Quetch in the Inter-Islands Ferry (Cit. Island) model',
              'Mrs. Brune (Inter-Islands rabbibunny) model',
              'Neighbor without gallic acid model',
              'Neighbor with gallic acid model',
              'Cart in Temple of Bu model',
              'Arrow in Temple of Bu model',
              'Painter from Citadel Island sewers model',
              'Rabbibunny in blue-white dressing model',
              'Nitro-Meca-Penguin model',
              'Flying saucer (UFO) with closed door and lights off model',
              'Flying saucer (UFO) with quarter-open door model',
              'Flying saucer (UFO) with closed door and lights on model',
              'Flying saucer (UFO) with closed door, lights on, and feet out model',
              'Royal saucer (UFO) with quarter-open door model',
              'Royal saucer (UFO) with closed door model',
              'Royal saucer (UFO) with closed door and feet in model',
              'Royal saucer (UFO) with closed door and feet out model',
              'Small flying saucer (UFO) model',
              'Boat is Esmers\' secret base model',
              'Franco guard with spike model',
              'Franco guard with spike model',
              'Franco guard with spike model',
              'Franco guard with spike model',
              'Sup in dark green dressing (clone of Johnny Rocket) model',
              'Sup in red dressing model',
              'Franco policeman with red helmet and gun model',
              'Franco policeman with black hat and gun model',
              'X-rayed franco red-helmet policeman model',
              'Franco policeman with green hat and stick model',
              'Franco survivor from Island CX model',
              'Yellow-red franco guard dressing (from secret base) model',
              'Baldino with space suit without helmet model',
              'Baldino with space suit with helmet in hand model',
              'Baldino with space suit with helmet model',
              'Light gray franco guard model',
              'Franco dissident model',
              'Light gray franco guard with gun model',
              'Light gray franco guard with tool model',
              'Mr. Bazoo (grobo in shop on Citadel Island) model',
              'Clerk in Mrs. Bloop\'s museum model',
              'Quetch guard of Temple Park model',
              'Quetch visitor of Mrs. Bloop\'s museum model',
              'Quetch guard of Temple Park with umbrella model',
              'Mrs. Bloop model',
              'Container in museum with Tunic model',
              'Container in museum without Tunic model',
              'Trunk in the sewers model',
              'Bird on Citadel Island model',
              'Little Tralu model',
              'Joe the Elf model',
              'Weather wizard model',
              'Creature in weather wizard\'s stove model',
              'Pharmacist model',
              'Sphero customer of pharmacy model',
              'Sphero customer of pharmacy with vacuum cleaner model',
              'Sphero customer of pharmacy with umbrella model',
              'The Citadel Island thief model',
              'The Citadel Island thief with customer\'s umbrella model',
              'Nomad grobo from Desert Island model',
              'A quetch model',
              'Female rabbibunny in swimming costume (in Hacienda bath) model',
              'Female grobo in Hacienda bath model',
              'Dean of the School of Magic model',
              'Female rabbibunny in the School of Magic model',
              'Ghost in the School of Magic model',
              'Sad grobo student in the School of Magic model',
              'Black nomad sphero from Desert Island model',
              'Male grobo in Hacienda bath model',
              'Empty space suit model',
              'Blowgun test magic symbol in the School of Magic model',
              'Hourglass (blowgun test) model',
              'Flask of gallic acid model',
              'Rabbibunny in shop on Desert Island model',
              'Rabbibunny child model',
              'Teacher of the kindergarten on Citadel Island model',
              'Grobo child model',
              'Quetch child 1 model',
              'Quetch child 2 with rope model',
              'Jerome Baldino model',
              'Memory viewer model',
              'Notes model',
              'Grobo in the hotel on Desert Island model',
              'Sub in blue dressing in the flying saucer model',
              'Female sup in the flying saucer model',
              'Female sup in the flying saucer with pull bell model',
              'Female sup in the flying saucer with pull bell and safety jacket model',
              'The translator model',
              'Rabbibunny with motorbike model',
              'Rabbibunny with motorbike and Twinsen with Tunic model',
              'Rabbibunny with motorbike and Twinsen with Wizard\'s Tunic model',
              'Bob with covered head model',
              'Bob with uncovered head model',
              'Sup in dark green dressing (clone of Johnny Rocket) model',
              'Johnny Rocket model',
              'Johnny Rocket in pyjamas model',
              'Elevator (big) model',
              'Robot on Otringal (prison guard) model',
              'Robot on Desert Island model',
              'Robot on Citadel Island model',
              'Felix with covered head model',
              'Felix with uncovered head model',
              'Crab model',
              'Top of giant crab model',
              'Front scissors (or feet) of giant crab model',
              'Ferry (you can call it hovercraft) model',
              'Dino-Fly with Twinsen with Tunic model',
              'Dino-Fly model',
              'Dino-Fly with Twinsen with Wizard\'s Tunic model',
              'Zed model',
              'Quetch, in love with the pharmacist model',
              'Mushroom model',
              'Raph\'s fiance model',
              'Piece of giant crab\'s scissor (or foot) model',
              'Light from a lighthouse model',
              'Twinsen and Zoé with the umbrella down model',
              'Quetch child 2 without rope model',
              'Rosa the cow model',
              'Quetch child 3 (on top of the pharmacy) model',
              'Quetch child 3 without his head model',
              'Quetch in black dressing (Quetch child 1\'s big brother) model',
              'Trash can (hidden Esmer) 1 model',
              'Trash can (hidden Esmer) 2 model',
              'The Citadel Island thies with his sister (Rabbibunny child) model',
              'The teacher of the kindergarten with Quetch child 2 model',
              'Luc, the boss, with his brother (Grobo child) model',
              'Franco guy with plates model',
              'Franco guy with glass model',
              'Sphero wizard (Ker\'aooc) model',
              'Female quetch wizard (Tabata)',
              'Grobo wizard model',
              'The usually drunk franco guy model',
              'Mosquibee guy 1 model',
              'Mosquibee guy 2 model',
              'Wannie guy 1 model',
              'Wannie guy 2 model',
              'Queen of the Mosquibees model',
              'Mosquibee Queen\'s ventilation guy model',
              'Quetch child #3 with plate with piece of cake model',
              'Female rabbibunny in the School of Magic model',
              'Sup sailor with glass model',
              'Twinsen with Tunic with piece of cake model',
              'Mosquibee guy with containe full of liquid model',
              'Zoé not pregnant anymore with child-carry thing 1 model',
              'Zoé not pregnant anymore with child-carry thing 2 model',
              'Franco nurse with franco child 1 model',
              'Franco child 2 model',
              'Wannie child 1 model',
              'Zed on the beach model',
              'Control-wheel for the woodbridge model',
              'Woodbridge transport wood model',
              'Giand spider (Citadel Island cliffs) model',
              'Moya the turtle model',
              'Silhuette of the turtle model',
              'The turtle slightly rising model',
              'The turtle greatly rising model',
              'The turtle almost out model',
              'Cactus (hidden Esmer) model',
              'The turtle-calling bell model',
              'Empty car model',
              'Clover box model',
              'One of the many desert flowers model',
              'Desert sphero 1 model',
              'Desert sphero 1 with guitar model',
              'Desert sphero 2 model',
              'Camel 1 model',
              'Camel 2 model',
              'Car with racer model',
              'Sphero bowl player model',
              'Quetch bowl player model',
              'Ball 1 (big gray ball) model',
              'Ball 2 (small red ball) model',
              'Quetch girl in swimming costume with book model',
              'Franco guy with beard (bowl player) model',
              'Sup in light green dressing (bowl player) model',
              'Quetch guard of Temple Park model',
              'Sup guy in swimming costume (Imerial Hotel) model',
              'Green shell (Joe the Elf imprisoned) model',
              'The Eye 1 of the School of Magic model',
              'The Eye 2 of the School of Magic model',
              'Chedil Amiradoo model',
              'The balsam flower model',
              'Piece of a plant model',
              'The sphero near Port-Ludo model',
              'Grobo policeman, guard of Temple Park model',
              'Rabbibunny, don\'t know, where he appears model',
              'Small yellow duck model',
              'Twinsen with Tunic and balloons model',
              'Twinsen with Wizard\'s Tunic and balloons model',
              'The balloons model',
              'Desert grobo model',
              'Old rabbibunny with guitar model',
              'Old rabbibunny with magic flute model',
              'The chest with old rabbibunny\'s domestic snake model',
              'The chest empty model',
              'Sup in space suit model',
              'Giraffe guy with camera on Zeelich model',
              'Ant guy with backpack on Zeelich model',
              'Ant guy 2 on Zeelich model',
              'Two-headed monster in Emperor\'s palace model',
              'Emperor\'s sup soldier 1 model',
              'Emperor\'s sup soldier 2 model',
              'Sup in swimming costume in water model',
              'Old sup lady in Imperial Hotel model',
              'Franco guard in Imperial Hotel model',
              'Franco policeman with stick down model',
              'Franco policeman with stick in hand model',
              'Female franco model',
              'Narrow electric barrier model',
              'Wider electric barrier model',
              'Mosquibee dissident model',
              'Sup guard of Emperor\'s palace model',
              'Sup guard of Emperor\'s palace with sword out model',
              'Leontine (zeppelin-boat of the old franco) model',
              'Leontine with the old franco aboard model',
              'Leontine with the old franco and Twinsen aboard model',
              'The old franco model',
              'Driver 1 of the motor-flyer model',
              'Driver 2 of the motor-flyer model',
              'The motor-flyer model',
              'Motor-flyer with driver 1 aboard model',
              'Motor-flyer with driver 1 and Twinsen aboard model',
              'Motor-flyer with driver 2 aboard model',
              'Motor-flyer with driver 2 and Twinsen aboard model',
              'Open crate in the undergas center model',
              'Closed crate in the undergas center model',
              'Open crate in the undergas center with Twinsen inside model',
              'Small closed crate model',
              'Franco policeman with red hat and gun on the car model',
              'Shotgun model',
              'Franco trooper model',
              'Franco trooper with UZI model',
              'Sup priest model',
              'Franco at the gas station on Otringal with gas-piston model',
              'Franco at the gas station on Otringal with hammer model',
              'Green gloom (alligator) model',
              'Green gloom (alligator) with tie model',
              'Gray gloom (alligator) model',
              'Small gloom (alligator), casino exit guard model',
              'Big gray gloom (alligator), holding Twinsen model',
              'Big gray gloom (alligator) model',
              'Franco with drum model',
              'Car at the gas station on Otringal model',
              'Zeelichian car without the gun model',
              'The gun of the car model',
              'Dark Monk\'s key model',
              'Fire ball model',
              'Franco survivor from Island CX model',
              'Kangaroo 1 model',
              'Kangaroo 2 model',
              'Franco priest model',
              'Dark Monk (hidden FunFrock) model',
              'FunFrock unihidding himself model',
              'Unhidden FunFrock model',
              'Unhidden FunFrock with sword out model',
              'Teleporting FunFrock model',
              'Standing stone 1 (for lava) model',
              'Standing stone 2 (for lava) model',
              'Mosquibee guy with beard model',
              'Wannie priest model',
              'Gas monster 1 model',
              'Silhuette of gas monster\'s head 1 model',
              'Gas monster 2 model',
              'Wannie guy 1 model',
              'Wannie guy 2 model',
              'Wannie guy 3 model',
              'Wannie guy 4 model',
              'Wannie child model',
              'Wannie child with red ball model',
              'Wannie grandma model',
              'Wannie grandma with plate with piece of tart model',
              'Wannie child capturing fireflies model',
              'Firefly model',
              'Frog model',
              'Ferryman with boat model',
              'Ferryman with boat with Twinsen aboard model',
              'Wannie guy 5 model',
              'Gem model',
              'Elevator to the undergas model',
              'Elevator to the undergas with Twinsen inside model',
              'Small gas monster 1 (blue) model',
              'Small gas monster 2 (gray) model',
              'Wannie guy with pick-axe model',
              'Undergas bulldozer model',
              'Undergas bulldozer pick-thing part 1 model',
              'Undergas bulldozer pick-thing part 2 model',
              'Little yellow pig model',
              'Main train wagon with wannie inside model',
              'Train wagon model',
              'Train wagon with stones model',
              '100% Firefly tart model',
              '5/6 Firefly tart model',
              '3/4 Firefly tart model',
              '2/3 Firefly tart model',
              'Wannie child\'s red ball model',
              'Wannie\'s glove model',
              'Gas monster 3 (gray) model',
              'Glass plate model',
              'Cover of the box with the mosquibees key fragment model',
              'Green mosquibee guy model',
              'Franco trooper with explosive box model',
              'Green mosquibee guy with flag model',
              'Mosquibee guy with Twinsen model',
              'Monkey monster with sword model',
              'Franco trooper with parachute model',
              'Mosquibee flag model',
              'Emperor\'s flag model',
              'Rope to get into the mosquibee fortress model',
              'Rope to get into the mosquibee fortress with Twinsen model',
              'Franco trooper with UZI and explosive ball model',
              'The two-zeppelin transport method to the elevator model',
              'Female dog on the Island of the Francos model',
              'Franco worker on the Island of the Francos model',
              'Franco with metal-detector on the Island of the Francos model',
              'Franco worker with red hat on the Island of the Francos model',
              'Mechanic owl model',
              'Gas monster 4 model',
              'Rocket-shooter on Island CX model',
              'Wannie guy with one glove model',
              'Sup in orange dressing (in Imperial Hotel and saucer) model',
              'Sup getting in garbage can in saucer model',
              'Sup getting in cactus in saucer model',
              'Wannie guy digging model',
              'Wannie child #1\'s toys model',
              'The wannies key fragment model',
              'Spider net model',
              'Old wannie model',
              'Old wannie with piece of tart model',
              'Monkey monster model',
              'Monkey monster with wooden box model',
              'Wannie child with captured firefly model',
              '"Feet" for something 1 model',
              '"Feet" for something 2 model',
              'Sup 1 with cigar in the undergas agency model',
              'Sup 2 sitting down with papers in the undergas agency model',
              'Gray ball model',
              'Fat yellow/black mosquibee guy model',
              'Blowtron model',
              'Green mosquibee guy with red flag model',
              'Lava fire ball model',
              'The wheel of fortune model',
              'Big gray gloom (alligator) with big stick model',
              'Female franco dancer model',
              'Franco fireman model',
              'Sup heavy metal guy in black dressing model',
              'Female franco dancer model',
              'The reptile-thing in the casino (come to papa) model',
              'Brown dog in the casino model',
              'Orange dog in the casino model',
              'Cyan dog in the casino model',
              'Yellow dog in the casino model',
              'Sup 1 in the casino model',
              'Sup 2 in the casino model',
              'Green gloom (alligator) 1 in the casino model',
              'Green gloom (alligator) 2 in the casino model',
              'Sailor (maybe pink wannie) 1 model',
              'Sailor (maybe pink wannie) 1 with gun model',
              'Glass of drink model',
              'Sailor (maybe pink wannie) 2 model',
              'Sailor (maybe pink wannie) 3 model',
              'Sailor (maybe brown wannie) model',
              'Sup sailor with glass of drink model',
              'Young wannie with stone in front of him model',
              'Half of a franco sitting down model',
              'Franco with gray hat and glass model',
              'Rick the sup model',
              'Silhuette of gas monster\'s head 2 model',
              'Gas monster 5 model',
              'Female franco model',
              'Can of gazogem model',
              'Sup 1 in the shop (I love Twinsun) model',
              'Sup 2 in the shop (I hate Twinsun) model',
              'Wizard\'s diploma model',
              'Ferry ticket model',
              'Customer\'s umbrella model',
              'Small spider model',
              'Pighead in red dressing with hammer (Emperor\'s palace) model',
              'Pighead in brown dressing with gardening tool (Emperor\'s palace) model',
              'Pighead in yellow dressing with broom (Emperor\'s palace) model',
              'Stan (from Time Commando) model',
              'Shy sup girl in Imperial Hotel model',
              'Light gray franco guard listening to music in Imperial Hotel model',
              'The above franco\'s tape player model',
              'Female franco in the shop on the Island of the Francos model',
              'Pick-axe model',
              'Glass-cleaning (at least I think) franco model',
              'Old franco scientist model',
              'Female franco nurse in the nursery model',
              'Franco child with red rapper hat model',
              'A small franco child modeld',
              'Brother of francos\' burgermaster (De La Fontaine) model',
              'Gas monster 6 (gray) model',
              'Silhuette of gas monster\'s head 3 model',
              'The emperor model',
              'The emperor\'s wife model',
              'Spikes in the protection spell\'s cave model',
              'Monster guarding the protection spell model',
              'The protection spell model',
              'Vertical electric bar of teleporting machine model',
              'Gray mechanic grobo near the end model',
              'Green mechanic grobo with box of missiles near the end model',
              'Quetch child 1 model',
              'Very long and thin vertical piece of metal model',
              'Two such pieces of metal model',
              'Grobo child model',
              'Rabbibunny child model',
              'Quetch child 2 model',
              'Extremely long and thin vertical/horizontal pieces of metal model',
              'Mechanic rabbibunny near the end model']
